# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install and prettier
      run: |
        sudo apt-get remove docker docker-engine docker.io containerd runc
        sudo apt-get update
        sudo apt-get install docker docker-engine containerd runc
        
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true
    
    # Cache
    - uses: actions/cache@v1.1.0
      with:
        path: Tag-Royale/Library
        key: Library-test-project-WebGL

    # Test
    - name: Run tests
      uses: webbertakken/unity-test-runner@v1.3
      with:
        projectPath: Tag-Royale
        unityVersion: 2019.4.4f1
    
    # Build
    - name: Unity - Builder
      uses: webbertakken/unity-builder@v1.1
      with:
        projectPath: Tag-Royale
        unityVersion: 2019.4.4f1
        targetPlatform: Android
        
    # Output
    - uses: actions/upload-artifact@v1
      with:
        name: Build
        path: build
